# Generated by Django 3.2.13 on 2023-10-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20231021_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an item type (e.g. vinyl record)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='Item_Type',
        ),
        migrations.DeleteModel(
            name='Item_Type',
        ),
        migrations.AddField(
            model_name='item',
            name='ItemType',
            field=models.ManyToManyField(help_text='Select an item type for this item.', to='project.ItemType'),
        ),
    ]
