# Generated by Django 3.2.13 on 2023-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20231021_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(help_text='Enter an item type (e.g. vinyl records)', max_length=200),
        ),
    ]
