# Generated by Django 3.2.13 on 2023-10-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_itemtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(help_text='Enter an item type (e.g. vinyl record).', max_length=200),
        ),
    ]
