# Generated by Django 3.2.13 on 2023-10-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_name_type_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
    ]
