# Generated by Django 3.2.13 on 2023-10-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_type_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Type',
            new_name='type',
        ),
    ]
