# Generated by Django 3.2.13 on 2023-10-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_iteminstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'ordering': ['due_back'], 'permissions': (('can_add_item', 'Add item to the item list'), ('can_delete_item', 'Delete item from the item list'))},
        ),
    ]
