# Generated by Django 3.2.13 on 2023-10-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.FloatField(default='123456789'),
        ),
    ]
