# Generated by Django 3.2.13 on 2023-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.FloatField(default=None),
        ),
    ]
