# Generated by Django 3.2.13 on 2023-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20231028_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
