# Generated by Django 3.2.13 on 2023-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=None, help_text='How may we help you today?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, help_text='Enter your full name', max_length=150),
        ),
    ]
