# Generated by Django 3.2.13 on 2023-11-15 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank='true', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 0000000000', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
