# Generated by Django 3.2.13 on 2023-11-27 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank='true', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='The format must be: 000-000-0000', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, help_text="Enter the item's natural language (e.g. English, French, Japanese, etc.)", max_length=200, null=True),
        ),
    ]
